export enum EVENT_KEY {
    Tab = "Tab",
    Enter = "Enter",
    Spacebar = " ",
    Esc = "Escape",
    ArrowDown = "ArrowDown",
    ArrowLeft = "ArrowLeft",
    ArrowRight = "ArrowRight",
    ArrowUp = "ArrowUp",
    Backspace = "Backspace",
    Down = "Down",
    Left = "Left",
    Right = "Right",
    Up = "Up",
}
